# Generated by Django 3.0.2 on 2020-01-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('date', models.DateField(blank=True, null=True)),
                ('hour', models.DateTimeField(blank=True, null=True)),
                ('route', models.TextField(default='')),
                ('equipment', models.TextField(default='')),
            ],
        ),
    ]
