# Generated by Django 3.0.2 on 2020-01-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200122_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='godzina',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
