# Generated by Django 3.0.2 on 2020-01-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_order_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startowa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprzęt', models.CharField(max_length=128)),
            ],
        ),
    ]
