# Generated by Django 3.0.2 on 2020-01-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_startowa_trasy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startowa',
            old_name='sprzęt',
            new_name='kajaki',
        ),
    ]
