# Generated by Django 3.0.2 on 2020-01-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200123_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startowa',
            name='kajaki',
        ),
    ]
