# Generated by Django 3.0.2 on 2020-01-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_startowa_kajaki'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Startowa',
        ),
    ]
