# Generated by Django 3.0.2 on 2020-01-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_startowa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startowa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obszar_nieedytowalny', models.CharField(max_length=128)),
            ],
        ),
    ]
