# Generated by Django 3.0.2 on 2020-01-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_startowa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imię', models.CharField(max_length=128)),
                ('nazwisko', models.CharField(max_length=128)),
                ('data', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('godzina', models.TimeField(blank=True, null=True)),
                ('trasa', models.TextField(default='')),
                ('sprzęt', models.TextField(default='')),
            ],
        ),
    ]
