# Generated by Django 3.0.2 on 2020-01-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200129_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='user',
        ),
    ]
