# Generated by Django 3.0.2 on 2020-01-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_useridentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrder',
        ),
        migrations.DeleteModel(
            name='UserIdentity',
        ),
    ]
