# Generated by Django 3.0.2 on 2020-01-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200129_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrder',
        ),
    ]
