# Generated by Django 3.0.2 on 2020-01-30 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_myorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrder',
        ),
    ]
