# Generated by Django 3.0.2 on 2020-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_myorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='myorder',
            name='trasa',
            field=models.IntegerField(choices=[(2, 'Krutyń - Ukta'), (1, 'Krutyń - Rosocha'), (3, 'Krutyń - Jezioro Mokre - Krutyń'), (0, 'Krutyń - Młyn')], default=0),
        ),
    ]
