# Generated by Django 3.0.2 on 2020-02-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200202_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='trasa',
            field=models.IntegerField(choices=[(2, 'Krutyń - Ukta'), (1, 'Krutyń - Rosocha'), (0, 'Krutyń - Młyn'), (3, 'Krutyń - Jezioro Mokre - Krutyń')], default=0),
        ),
    ]
