# Generated by Django 3.0.2 on 2020-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200202_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='trasa',
            field=models.IntegerField(choices=[(3, 'Krutyń - Jezioro Mokre - Krutyń'), (2, 'Krutyń - Ukta'), (0, 'Krutyń - Młyn'), (1, 'Krutyń - Rosocha')], default=0),
        ),
    ]
