# Generated by Django 3.0.2 on 2020-02-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200202_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='data',
            field=models.IntegerField(choices=[(0, '03-02-2020'), (1, '04-02-2020'), (2, '05-02-2020'), (3, '06-02-2020'), (4, '07-02-2020'), (5, '08-02-2020'), (6, '09-02-2020')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myorder',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myorder',
            name='godzina',
            field=models.IntegerField(choices=[(0, '9:00'), (1, '9:15'), (2, '9:30'), (3, '9:45'), (4, '10:00'), (5, '10:15'), (5, '10:30'), (7, '10:45'), (8, '11:00'), (9, '11:15'), (10, '11:30'), (11, '11:45'), (12, '12:00')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myorder',
            name='trasa',
            field=models.IntegerField(choices=[(0, 'Krutyń - Młyn (3km)'), (1, 'Krutyń - Rosocha (6km)'), (2, 'Krutyń - Ukta (13km)'), (3, 'Krutyń - Jezioro Mokre - Krutyń (10km)')]),
        ),
    ]
