# Generated by Django 3.0.2 on 2020-02-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200203_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='WyborKajakow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kajaki', models.IntegerField(choices=[(0, 'Eoli'), (2, 'Traper'), (3, 'Family'), (1, 'Finder')])),
            ],
        ),
        migrations.AlterField(
            model_name='myorder',
            name='sprzęt',
            field=models.IntegerField(),
        ),
    ]
