# Generated by Django 3.0.2 on 2020-02-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200203_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WyborKajakow',
        ),
    ]
