# Generated by Django 3.0.2 on 2020-02-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_delete_wyborkajakow'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentToChose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder', models.CharField(max_length=100)),
                ('eoli', models.CharField(max_length=100)),
                ('traper', models.CharField(max_length=100)),
            ],
        ),
    ]
