# Generated by Django 3.0.2 on 2020-02-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_equipmenttochose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyOrder',
        ),
    ]
