# Generated by Django 3.0.2 on 2020-02-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_myorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='sprzęt',
        ),
        migrations.DeleteModel(
            name='EquipmentToChose',
        ),
    ]
