# Generated by Django 3.0.2 on 2020-02-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200203_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentToChose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=50)),
                ('ilosc', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.AddField(
            model_name='myorder',
            name='sprzęt',
            field=models.ManyToManyField(to='main.EquipmentToChose'),
        ),
    ]
