# Generated by Django 3.0.2 on 2020-02-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200204_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jedynki',
        ),
    ]
