# Generated by Django 3.0.2 on 2020-02-04 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200204_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorder',
            name='sprzęt',
        ),
        migrations.AddField(
            model_name='myorder',
            name='kod',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name='EquipmentToChose',
        ),
    ]
