# Generated by Django 3.0.2 on 2020-02-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20200205_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termin', models.DateField(default='05-02-2020')),
            ],
        ),
    ]
