# Generated by Django 3.0.2 on 2020-02-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_terminy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorder',
            name='data',
            field=models.IntegerField(choices=[(0, '06-02-2020'), (1, '07-02-2020'), (2, '08-02-2020'), (3, '09-02-2020'), (4, '10-02-2020'), (5, '11-02-2020'), (6, '12-02-2020')]),
        ),
        migrations.AlterField(
            model_name='terminy',
            name='termin',
            field=models.DateField(),
        ),
    ]
